-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 09:47:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `hotel`;
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`member` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(12) NULL,
  `pw` VARCHAR(20) NULL,
  `name` VARCHAR(50) NULL,
  `birth` DATE NULL,
  `tel` VARCHAR(11) NULL,
  `email` VARCHAR(64) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `post` VARCHAR(5) NULL,
  `address` VARCHAR(45) NULL,
  `detail_address` VARCHAR(45) NULL,
  `marketing` VARCHAR(1) NULL,
  `jdate` TIMESTAMP NULL DEFAULT current_timestamp,
  `state` VARCHAR(2) NULL DEFAULT '가입',
  `grade` INT NULL DEFAULT 1,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hotel`.`reservation_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation_adm` (
  `rezAdm_no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `title_s` TEXT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `thum` BLOB NULL,
  `content` TEXT NULL,
  `benefits` TEXT NULL,
  `views` INT NULL,
  `pkg_rate` DOUBLE NULL,
  `rsv_write` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rezAdm_no`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `hotel`.`reservation`
-- -----------------------------------------------------
 DROP TABLE `hotel`.`reservation`;
CREATE TABLE IF NOT EXISTS `hotel`.`reservation` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `date_write` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `room_count` INT NOT NULL DEFAULT 1,
  `count_adult` INT NULL,
  `count_elementary` INT NULL,
  `count_child` INT NULL,
  `count_baby` INT NULL,
  `count_all` INT NOT NULL,
  `promotion_name` VARCHAR(45) NULL,
  `promotion_code` long NULL,
  `breakfast_adult` INT NULL,
  `breakfast_child` INT NULL,
  `price_product` INT NOT NULL,
  `price_service` INT NOT NULL,
  `price_bed` INT NOT NULL,
  `price_options` INT NOT NULL,
  `price_member` INT NOT NULL,
  `price_point` INT NOT NULL,
  `price_total` INT NOT NULL,
  `price_result` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NOT NULL,
  `add_requests` TEXT NULL,
  `views` INT NULL DEFAULT 0,
  `state` VARCHAR(45) NOT NULL DEFAULT '예약대기',
  `rsv_adm_no` INT NOT NULL,
  `writer` INT NOT NULL,
  `rooms_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_reservation_reservation_adm1_idx` (`rsv_adm_no` ASC),
  INDEX `fk_reservation_member1_idx` (`writer` ASC),
  INDEX `fk_reservation_rooms1_idx` (`rooms_no` ASC),
  CONSTRAINT `fk_reservation_reservation_adm1`
    FOREIGN KEY (`rsv_adm_no`)
    REFERENCES `hotel`.`reservation_adm` (`rezAdm_no`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservation_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `hotel`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservation_rooms1`
    FOREIGN KEY (`rooms_no`)
    REFERENCES `hotel`.`rooms` (`no`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hotel`.`reservation_attach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation_attach` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `size` INT NOT NULL,
  `rsv_adm` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_attach_room_adm1_idx` (`rsv_adm` ASC),
  CONSTRAINT `fk_attach_room_adm1`
    FOREIGN KEY (`rsv_adm`)
    REFERENCES `hotel`.`reservation_adm` (`rezAdm_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hotel`.`reservation_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation_promotion` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` INT NOT NULL,
  `date_created` TIMESTAMP NULL,
  `date_use` TIMESTAMP NULL,
  `date_expriation` TIMESTAMP NULL,
  `room_customer_no` INT NOT NULL,
  `room_adm_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_room_promotion_room_customer1_idx` (`room_customer_no` ASC),
  INDEX `fk_room_promotion_room_adm1_idx` (`room_adm_no` ASC),
  CONSTRAINT `fk_room_promotion_room_customer1`
    FOREIGN KEY (`room_customer_no`)
    REFERENCES `hotel`.`reservation` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_promotion_room_adm1`
    FOREIGN KEY (`room_adm_no`)
    REFERENCES `hotel`.`reservation_adm` (`rezAdm_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `hotel`.`rez_adm_room_type`
-- -----------------------------------------------------
-- DROP TABLE `hotel`.`rez_adm_room_type`;
CREATE TABLE IF NOT EXISTS `hotel`.`rez_adm_room_type` (
  `rez_adm_room_no` INT NOT NULL AUTO_INCREMENT,
  `rez_adm` INT NULL,
  `room_type` INT NULL,
  `title` VARCHAR(150) NULL,
  `benefit` TEXT NULL,
  INDEX `fk_reservation_adm_has_room_type_room_type1_idx` (`room_type` ASC),
  INDEX `fk_reservation_adm_has_room_type_reservation_adm1_idx` (`rez_adm` ASC),
  PRIMARY KEY (`rez_adm_room_no`),
  CONSTRAINT `fk_reservation_adm_has_room_type_reservation_adm1`
    FOREIGN KEY (`rez_adm`)
    REFERENCES `hotel`.`reservation_adm` (`rezAdm_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_adm_has_room_type_room_type1`
    FOREIGN KEY (`room_type`)
    REFERENCES `hotel`.`room_type` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `hotel`.`point_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`point_event` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `state` INT NOT NULL,
  `amount` INT NOT NULL,
  `trans_date` TIMESTAMP NULL,
  `expire_date` TIMESTAMP NULL,
  `member_no` INT NOT NULL,
  `reservation_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_point_event_member1_idx` (`member_no` ASC),
  INDEX `fk_point_event_reservation1_idx` (`reservation_no` ASC),
  CONSTRAINT `fk_point_event_member1`
    FOREIGN KEY (`member_no`)
    REFERENCES `hotel`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_point_event_reservation1`
    FOREIGN KEY (`reservation_no`)
    REFERENCES `hotel`.`reservation` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`point_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`point_detail` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `state` INT NOT NULL,
  `amount` INT NOT NULL,
  `point_event_no` INT NOT NULL,
  `trans_date` TIMESTAMP NULL,
  `expire_date` TIMESTAMP NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_point_detail_point_event1_idx` (`point_event_no` ASC),
  CONSTRAINT `fk_point_detail_point_event1`
    FOREIGN KEY (`point_event_no`)
    REFERENCES `hotel`.`point_event` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`restaurants`
-- -----------------------------------------------------
-- DROP TABLE `hotel`.`restaurants`;
CREATE TABLE IF NOT EXISTS `hotel`.`restaurants` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `date_reserve` DATE NULL,
  `time_meal` VARCHAR(45) NULL,
  `date_write` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `count_adult` INT NULL,
  `count_elementary` INT NULL,
  `count_child` INT NULL,
  `count_baby` INT NULL,
  `count_all` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `add_request` TEXT NULL,
  `state` VARCHAR(45) NOT NULL DEFAULT '예약대기',
  `writer` INT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_restaurants_member1_idx` (`writer` ASC) ,
  CONSTRAINT `fk_restaurants_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `hotel`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`restaurants_adm`
-- -----------------------------------------------------
-- DROP TABLE `hotel`.`restaurants_adm`;
CREATE TABLE IF NOT EXISTS `hotel`.`restaurants_adm` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `cate` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `time_lunch` TIMESTAMP NULL,
  `time_dinner` TIMESTAMP NULL,
  `num_of_seat` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `rt_atc_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_restaurants_adm_restaurants1_idx` (`rt_atc_no` ASC) ,
  CONSTRAINT `fk_restaurants_adm_restaurants1`
    FOREIGN KEY (`rt_atc_no`)
    REFERENCES `hotel`.`restaurants` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`rastaurants_attach`
-- -----------------------------------------------------
-- DROP TABLE `hotel`.`rastaurants_attach`;
CREATE TABLE IF NOT EXISTS `hotel`.`rastaurants_attach` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `size` INT NULL,
  `rt_adm_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_rastaurants_attach_restaurants_adm1_idx` (`rt_adm_no` ASC) ,
  CONSTRAINT `fk_rastaurants_attach_restaurants_adm1`
    FOREIGN KEY (`rt_adm_no`)
    REFERENCES `hotel`.`restaurants_adm` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
