-- MySQL Script generated by MySQL Workbench
-- Thu Jul  8 14:34:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `hotel`.`restaurants`
-- -----------------------------------------------------
DROP TABLE `hotel`.`restaurants`;
CREATE TABLE IF NOT EXISTS `hotel`.`restaurants` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `date_reserve` DATE NULL,
  `time_meal` VARCHAR(45) NULL,
  `date_write` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `count_adult` INT NULL,
  `count_elementary` INT NULL,
  `count_child` INT NULL,
  `count_baby` INT NULL,
  `count_all` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `add_request` TEXT NULL,
  `state` VARCHAR(45) NOT NULL DEFAULT '예약대기',
  `writer` INT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_restaurants_member1_idx` (`writer` ASC) ,
  CONSTRAINT `fk_restaurants_member1`
    FOREIGN KEY (`writer`)
    REFERENCES `hotel`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`restaurants_adm`
-- -----------------------------------------------------
DROP TABLE `hotel`.`restaurants_adm`;
CREATE TABLE IF NOT EXISTS `hotel`.`restaurants_adm` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `cate` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `time_lunch` TIMESTAMP NULL,
  `time_dinner` TIMESTAMP NULL,
  `num_of_seat` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `rt_atc_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_restaurants_adm_restaurants1_idx` (`rt_atc_no` ASC) ,
  CONSTRAINT `fk_restaurants_adm_restaurants1`
    FOREIGN KEY (`rt_atc_no`)
    REFERENCES `hotel`.`restaurants` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`rastaurants_attach`
-- -----------------------------------------------------
DROP TABLE `hotel`.`rastaurants_attach`;
CREATE TABLE IF NOT EXISTS `hotel`.`rastaurants_attach` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `size` INT NULL,
  `rt_adm_no` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_rastaurants_attach_restaurants_adm1_idx` (`rt_adm_no` ASC) ,
  CONSTRAINT `fk_rastaurants_attach_restaurants_adm1`
    FOREIGN KEY (`rt_adm_no`)
    REFERENCES `hotel`.`restaurants_adm` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
